apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  # Konfiguracja wyglądu i ustawień ogólnych
  settings.yaml: |
    title: Home Server Dashboard
    background: https://i.pinimg.com/1200x/e8/15/2a/e8152a5d0516df591415ee0eba5d29d8.jpg
    cardBlur: sm
    theme: dark
    color: slate
    showStats: true

  # Układ grup na ekranie
  services.yaml: |
    - Home Automation:
        - Home Assistant:
            icon: home-assistant.svg
            href: https://homeassistant.tail318b16.ts.net
            description: Zarządzanie domem i automatyzacja
            ping: https://homeassistant.tail318b16.ts.net
        - Zigbee2MQTT:
            icon: zigbee2mqtt.svg
            href: https://home-automation-zigbee2mqtt-ingress-ingress.tail318b16.ts.net
            description: Mostek urządzeń Zigbee
            ping: https://home-automation-zigbee2mqtt-ingress-ingress.tail318b16.ts.net

    - Network & Infrastructure:
        - Pi-hole:
            icon: pi-hole.svg
            href: https://pihole.tail318b16.ts.net/admin/
            description: Blokowanie reklam i serwer DNS
            ping: https://pihole.tail318b16.ts.net/admin/

    - Tools & Utilities:
        - Stirling-PDF:
            icon: stirling-pdf.svg
            href: https://stirling-pdf-stirling-pdf-ingress-ingress.tail318b16.ts.net
            description: Narzędzie do edycji i konwersji PDF
            ping: https://stirling-pdf-stirling-pdf-ingress-ingress.tail318b16.ts.net

  # Dodatkowe zakłaki/przydatne linki (opcjonalnie)
  bookmarks.yaml: |
    - Developer:
        - GitHub:
            - abbr: PR
              href: https://github.com/PrzemyslawSwierzewski/home-ops/tree/main
    - Youtube:
        - Youtube:
            - abbr: YT
              href: https://www.youtube.com/
    - Google:
        - Google:
            - abbr: GE
              href: https://www.google.com/


  # Widgety na samej górze strony (zegar, wykorzystanie zasobów)
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /
    - search:
        provider: google
        target: _blank