apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Komponenty Fluxa (domyślne)
  - flux-system/gotk-components.yaml
  - flux-system/gotk-sync.yaml

  # Home assistant
  - namespace.yaml
  - home_Assistant-PVC.yaml
  - mosquitto-PVC.yaml
  - zigbee-PVC.yaml
  - zigbee-configmap.yaml
  - home_Assistant-deployment.yaml
  - mosquitto-deployment.yaml
  - zigbee-deployment.yaml
  - home_Assistant-service.yaml
  - mosquitto-service.yaml
  - zigbee-service.yaml
  - home_Assistant-ingress.yaml
  - zigbee-ingress.yaml

  # Tailscale
  - tailscale-namespace.yaml
  - tailscale-operator.yaml

  # Pihole
  - pihole-namespace.yaml
  - pihole-service.yaml
  - pihole-deployment.yaml
  - pihole-ingress.yaml
  - pihole-PVC.yaml
