apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
  labels:
    app: stirling-pdf
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      containers:
        - name: stirling-pdf
          image: frooodle/s-pdf:2.14.2-ultra-lite
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DOCKER_ENABLE_SECURITY
              value: "false"
            - name: SYSTEM_DEFAULT_LOCALE
              value: "pl_PL"
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 2
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            failureThreshold: 5
            initialDelaySeconds: 60
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 2Gi
