apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      initContainers:
      - name: init-config
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'cp /tmp/config/configuration.yaml /app/data/configuration.yaml']
        volumeMounts:
        - name: config-template
          mountPath: /tmp/config
        - name: data
          mountPath: /app/data
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "Europe/Warsaw"
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /app/data
          name: data
        - mountPath: /dev/ttyUSB0
          name: zigbee-adapter
      volumes:
      - name: config-template
        configMap:
          name: zigbee2mqtt-config
      - name: data
        persistentVolumeClaim:
          claimName: zigbee2mqtt-pvc
      - name: zigbee-adapter
        hostPath:
          path: /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_8c676bf57af3ef11b2cdba1b6d9880ab-if00-port0
